
rss: atom.xml

# html lang
language: en

# main menu navigation
menu:
  首页: /
  关于: /about
  # Contact: /contact
  # Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/page.css
- /css/code.css
- /css/font-awesome.css

# scripts loaded in the end of the body
scripts:
- /js/syefe.js

